"""Cut a ChatGPT parts sheet into rig parts and write a rig definition.
usage: python3 cut.py <name> ; reads <name>/parts.json:
  {"parts": {"head":[w,h,x,y,cropTopFrac,cropBotFrac,targetH, widthStretch], ...},
   "joints": {...see below...}}
Joint fractions are relative to each part image (0..1)."""
import json,subprocess,sys
n=sys.argv[1]; cfg=json.load(open(f'{n}/parts.json'))
sizes={}
for part,(w,h,x,y,t0,t1,th,ws) in cfg['parts'].items():
    cy=y+int(h*t0); ch=int(h*(t1-t0))
    tw=round(w*th/ch*ws)
    # clean the semi-transparent glow some sheets have, keep anti-aliased edges
    subprocess.run(['magick',f'{n}/sheet.png','-crop',f'{w}x{ch}+{x}+{cy}','+repage','-channel','A','-level','45%,70%','+channel',
                    '-trim','+repage','-resize',f'{tw}x{th}!','-strip',f'{n}/{part}.png'],check=True)
    sizes[part]=[tw,th]
J=cfg['joints']
def P(part,fx,fy): w,h=sizes[part]; return [round(w*fx),round(h*fy)]
def limb(idp,part,attach_part,afx,afy,pfx,pfy,z,far,children=None):
    d={'id':idp,'src':f'{n}/{part}.png','size':sizes[part],'attach':P(attach_part,afx,afy),'pivot':P(part,pfx,pfy),'z':z}
    if far: d['tint']='brightness(.72)'
    if children: d['children']=children
    return d
kids=[]
for side,far,zu,zt in [('R',True,-3,-2),('L',False,2,-1)]:
    fore=limb('elbow'+side,'forearm','upperarm',.5,J['elbow'][0],.5,J['elbow'][1],-1,far)
    kids.append(limb('shoulder'+side,'upperarm','torso',J['shoulder'][0],J['shoulder'][1],.5,J['shoulderPivot'],zu,far,[fore]))
    shin=limb('knee'+side,'shin','thigh',.5,J['knee'][0],J['shinPivot'][0],J['knee'][1],-1,far)
    kids.append(limb('hip'+side,'thigh','torso',J['hip'][0],J['hip'][1],.5,J['thighPivot'],zt,far,[shin]))
kids.append({'id':'neck','src':f'{n}/head.png','size':sizes['head'],'attach':P('torso',*J['neck']),'pivot':P('head',*J['headPivot']),'z':1})
order=['shoulderR','hipR','hipL','neck','shoulderL']; kids.sort(key=lambda k:order.index(k['id']))
root={'id':'torso','src':f'{n}/torso.png','size':sizes['torso'],'pivot':P('torso',J['hip'][0],J['hip'][1]),'z':0,'children':kids}
var=cfg['var']
open(f'{n}/rig-def.js','w').write(f"// generated by tools/rig/cut.py from {n}/parts.json\nwindow.{var} = "+json.dumps({'height':1600,'stride':cfg.get('stride',1300),'root':root})+";\n")
print(n,sizes)
